# -*- coding: utf-8 -*-
"""seed_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BR4FgNO1hZJyMP4PT0so5gm8IS4pN5HU
"""



from app import app
from models import db, Supplier, Product, Order

with app.app_context():

    supplier1 = Supplier(
        supplier_name="Tech Supplies Inc",
        contact_email="tech@example.com",
        phone_number="1234567890"
    )

    supplier2 = Supplier(
        supplier_name="Office World",
        contact_email="office@example.com",
        phone_number="9876543210"
    )

    db.session.add_all([supplier1, supplier2])
    db.session.commit()

    product1 = Product(
        product_name="Laptop",
        category="Electronics",
        price=1200,
        quantity=10,
        supplier_id=supplier1.supplier_id
    )

    product2 = Product(
        product_name="Printer",
        category="Office",
        price=300,
        quantity=5,
        supplier_id=supplier2.supplier_id
    )

    db.session.add_all([product1, product2])
    db.session.commit()

    order1 = Order(
        product_id=product1.product_id,
        order_quantity=2,
        order_date="2026-05-13"
    )

    db.session.add(order1)
    db.session.commit()

    print("Sample data inserted successfully")

